name = "IDFCurves"
uuid = "17afcda4-a678-4b99-aabd-b1f8835dcb1e"
authors = ["Jonathan Jalbert", "Paul Mathivon", "Auguste Paoli"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
